### ISSUE TITLE
[feature-request] Easier support between juliaup and PyJulia

### ISSUE THREAD

**Issue by hayesall** [JuliaLang/juliaup#297]
I'm running into a pain point between `juliaup` and `PyJulia`, possibly due to the `julialauncher` name.

`PyJulia` (and possibly other 3rd party libraries) seem to look for a `julia` binary on the PATH.

This *might* need to be transferred to the [PyJulia repository](https://github.com/JuliaPy/pyjulia).

## Steps to Reproduce

I was hoping that creating an alias `julia=julialauncher` would be sufficient:

```bash
# Add this line to the .bashrc:
alias julia='julialauncher'
```

```bash
pip install julia
```

Trying to import from `julia` in Python:

```python
from julia import Base
```

... raises an error that `julia` cannot be found:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/site-packages/julia/core.py", line 248, in load_module
    elif self.julia.isafunction(juliapath):
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/site-packages/julia/core.py", line 468, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/site-packages/julia/juliainfo.py", line 68, in load
    proc = subprocess.Popen(
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hayesall/miniconda3/envs/debug/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'julia'
```

### Version Info:

- juliaup: `1.6.2-alpha.0`
- Julia: `1.7.2`
- PyJulia: `0.5.7`
- Python: `3.8.18`
- OS: `Debian GNU/Linux 10`

**Comment by uncomfyhalomacro** [comment]
try symlinking `julialauncher` to `julia`

by running `sudo ln -svf "$(which julialauncher)" /usr/bin/julia` 

Disclaimer: i dont use pyjulia

**Comment by hayesall** [comment]
I've been building against the master branch with the Ubuntu/Debian systems I work on (i.e. `cargo build --release`).

My bad! I didn't realize the "official" distributions created the symlink by default.
