### ISSUE TITLE
The second instance of VSCode can't find `julia.executablePath`

### ISSUE THREAD

**Issue by eliascarv** [JuliaLang/juliaup#643]
When I open the first VSCode window, the Julia Extension works perfectly. But, when I open the second VSCode window, the Julia Extension can't find the `julia.executablePath`.

Print:
![Captura de tela de 2023-05-16 16-06-04](https://github.com/JuliaLang/juliaup/assets/73039601/236f980a-7706-496d-b832-0b93d42e5bfc)

juliaup info:
```shell
➜  ~ juliaup --version
Juliaup 1.8.16

➜  ~ juliaup status
 Default  Channel  Version                Update 
-------------------------------------------------
          lts      1.6.7+0.x64.linux.gnu         
       *  release  1.9.0+0.x64.linux.gnu
```

**Comment by davidanthoff** [comment]
What is your `julia.executablePath` setting? Also, can you copy-paste the output of the Julia extension Output channel from VS Code here?

**Comment by eliascarv** [comment]
My `julia.executablePath` setting is empty (I think this is the default value):

![Captura de tela de 2023-08-06 13-25-13](https://github.com/JuliaLang/juliaup/assets/73039601/c081451c-de3f-458f-b82a-acbeffe5df9f)

This is the Extension Output:
```
2023-08-06 13:29:05.773 [info] Extension host with pid 8978 started
2023-08-06 13:29:05.773 [info] Skipping acquiring lock for /home/elias/.config/Code/User/workspaceStorage/a883bb1159e165fa2aed30bc7dbfaa2e.
2023-08-06 13:29:05.898 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-08-06 13:29:05.899 [info] ExtensionService#_doActivateExtension julialang.language-julia, startup: false, activationEvent: 'onLanguage:julia'
2023-08-06 13:29:06.423 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'api', root cause: julialang.language-julia
2023-08-06 13:29:06.451 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-08-06 13:29:06.535 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-08-06 13:29:06.535 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-08-06 13:29:06.535 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-08-06 13:29:06.655 [info] Eager extensions activated
2023-08-06 13:29:06.695 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-08-06 13:29:06.695 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-08-06 13:29:06.696 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-08-06 13:29:06.705 [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
2023-08-06 13:29:06.739 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-08-06 13:29:07.408 [error] TypeError: Cannot read properties of undefined (reading 'file')
    at /home/elias/.vscode/extensions/julialang.language-julia-1.47.2/src/jlpkgenv.ts:198:29
    at Generator.next (<anonymous>)
    at s (/home/elias/.vscode/extensions/julialang.language-julia-1.47.2/src/interactive/workspace.ts:282:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-06 13:29:07.506 [error] TypeError: Cannot read properties of undefined (reading 'getVersion')
    at t.JuliaNotebookFeature.<anonymous> (/home/elias/.vscode/extensions/julialang.language-julia-1.47.2/src/notebook/notebookFeature.ts:76:38)
    at Generator.next (<anonymous>)
    at s (/home/elias/.vscode/extensions/julialang.language-julia-1.47.2/src/juliaexepath.ts:325:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by eliascarv** [comment]
This error only happens when I have two VSCode windows open running the Julia extension. And it also only happens when I use juliaup. When I use the official Julia binaries with symlinks everything works perfectly.

**Comment by eliascarv** [comment]
It works now! Thank you for your attention.
